/*
 * Data Fetching
*/
const FETCH_HISTORICALS_REQUEST = 'FETCH_HISTORICALS_REQUEST'
const FETCH_HISTORICALS_SUCCESS = 'FETCH_HISTORICALS_SUCCESS'
const FETCH_HISTORICALS_FAILURE = 'FETCH_HISTORICALS_FAILURE'


export default {
  FETCH_HISTORICALS_REQUEST,
  FETCH_HISTORICALS_SUCCESS,
  FETCH_HISTORICALS_FAILURE
}
